resources:

- name: git-resource1
  type: git
  check_every: 15s
  source:
    uri: git@github.com:tredfield/test-prs.git
    private_key: {{github_private_key}}

- name: git-resource2
  type: git
  check_every: 5s
  source:
    uri: git@github.com:tredfield/demo-concourse.git
    private_key: {{github_private_key}}

- name: git-resource3
  type: git
  check_every: 15s
  source:
    uri: git@github.com:tredfield/test-shippable.git
    private_key: {{github_private_key}}

- name: bump-job2
  type: semver
  source:
    driver: git
    uri: git@github.com:tredfield/demo-concourse.git
    branch: master
    initial_version: 0.0.1
    file: version
    private_key: {{trav_github_private_key}}


jobs:
- name: job1
  plan:
  - get: git-resource1
    trigger: true
  - put: bump-job2
    params: {bump: patch}


- name: job2
  plan:
  - get: git-resource1
    passed: [job1]
  - get: git-resource2
    trigger: true
  - get: git-resource3
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world!"]
